### ISSUE TITLE
CORS request fails

### ISSUE THREAD

**Issue by OleksiyRudenko** [marcolussetti/adventofcode-percenter#5]
Network request fails with 403 response on "Compute!" action at main.js line 22:
``fetch(`https://marcors.ferned.net/https://adventofcode.com/${year}/stats`)``

Not sure if it is an issue on marcors side or adventofcode has added any restrictions on their side.

**Comment by OleksiyRudenko** [comment]
Looks like cors-anywhere have added extra business logic to their code to prevent service abuse (see https://github.com/Rob--W/cors-anywhere/issues/301) that requires user action to enable functionality.

Not sure if you would want to resolve this by simply introducing a by-pass on marcors side.

Your tool is just great and I used it in past two seasons of Advent of Code. I truly believe it is underrated. Thank you for making it.

**Comment by OleksiyRudenko** [comment]
I was using obviously obsolete tool instance at https://aocpercenter.marcolussetti.com/

My apologies for wrong alarms

**Comment by marcolussetti** [comment]
Hey @OleksiyRudenko -- you are extremely kind as always :)

Yes with the cors-anywhere project essentially shutting down their demo site I had to use my own cors-anywhere instance. It has a whitelist and unfortunately I had forgotten we have the aocpercentage.marcolussetti.com URL as well. That should work now, thanks for letting me know!
